"""Add system_settings table

Revision ID: 25365a842808
Revises: a7aec5b22bd9
Create Date: 2026-05-11 10:05:43.098264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25365a842808'
down_revision: Union[str, Sequence[str], None] = 'a7aec5b22bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.drop_index(op.f('idx_admin_logs_action_type'), table_name='admin_logs')
    op.drop_index(op.f('idx_admin_logs_admin_user'), table_name='admin_logs')
    op.drop_index(op.f('idx_admin_logs_created_at'), table_name='admin_logs')
    op.drop_index(op.f('idx_conv_history_conversation_id'), table_name='conversation_history')
    op.drop_index(op.f('idx_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_last_message'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_store_id'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_status'), table_name='conversations')
    op.drop_index(op.f('idx_conversations_user_id'), table_name='conversations')
    op.drop_constraint(op.f('conversations_session_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('idx_messages_conversation_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_created_at'), table_name='messages')
    op.drop_index(op.f('idx_messages_role'), table_name='messages')
    op.drop_index(op.f('idx_messages_user_id'), table_name='messages')
    op.drop_index(op.f('idx_messages_whatsapp_id'), table_name='messages')
    op.drop_index(op.f('idx_rag_documents_active'), table_name='rag_documents', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_rag_documents_category'), table_name='rag_documents')
    op.drop_index(op.f('idx_rag_documents_content_trgm'), table_name='rag_documents', postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_rag_documents_embedding'), table_name='rag_documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_rag_documents_type'), table_name='rag_documents')
    op.drop_index(op.f('idx_rag_retrievals_conversation_id'), table_name='rag_retrievals')
    op.drop_index(op.f('idx_rag_retrievals_created_at'), table_name='rag_retrievals')
    op.drop_index(op.f('idx_rag_retrievals_message_id'), table_name='rag_retrievals')
    op.drop_index(op.f('idx_rag_retrievals_user_id'), table_name='rag_retrievals')
    op.drop_index(op.f('idx_sessions_active'), table_name='sessions', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_store_id'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_token'), table_name='sessions')
    op.drop_index(op.f('idx_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('idx_stores_is_primary'), table_name='stores', postgresql_where='(is_primary = true)')
    op.drop_index(op.f('idx_stores_user_id'), table_name='stores')
    op.drop_index(op.f('idx_stores_yaburu_id'), table_name='stores')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_phone'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_phone'), 'users', ['phone_number'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_stores_yaburu_id'), 'stores', ['yaburu_store_id'], unique=False)
    op.create_index(op.f('idx_stores_user_id'), 'stores', ['user_id'], unique=False)
    op.create_index(op.f('idx_stores_is_primary'), 'stores', ['is_primary'], unique=False, postgresql_where='(is_primary = true)')
    op.create_index(op.f('idx_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_token'), 'sessions', ['session_token'], unique=False)
    op.create_index(op.f('idx_sessions_store_id'), 'sessions', ['store_id'], unique=False)
    op.create_index(op.f('idx_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('idx_sessions_active'), 'sessions', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_rag_retrievals_user_id'), 'rag_retrievals', ['user_id'], unique=False)
    op.create_index(op.f('idx_rag_retrievals_message_id'), 'rag_retrievals', ['message_id'], unique=False)
    op.create_index(op.f('idx_rag_retrievals_created_at'), 'rag_retrievals', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_rag_retrievals_conversation_id'), 'rag_retrievals', ['conversation_id'], unique=False)
    op.create_index(op.f('idx_rag_documents_type'), 'rag_documents', ['document_type'], unique=False)
    op.create_index(op.f('idx_rag_documents_embedding'), 'rag_documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index(op.f('idx_rag_documents_content_trgm'), 'rag_documents', ['content'], unique=False, postgresql_ops={'content': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_rag_documents_category'), 'rag_documents', ['category'], unique=False)
    op.create_index(op.f('idx_rag_documents_active'), 'rag_documents', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_messages_whatsapp_id'), 'messages', ['whatsapp_message_id'], unique=False)
    op.create_index(op.f('idx_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.create_index(op.f('idx_messages_role'), 'messages', ['role'], unique=False)
    op.create_index(op.f('idx_messages_created_at'), 'messages', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_session_id_fkey'), 'conversations', 'stores', ['session_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('idx_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index(op.f('idx_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('idx_conversations_store_id'), 'conversations', ['store_id'], unique=False)
    op.create_index(op.f('idx_conversations_last_message'), 'conversations', [sa.literal_column('last_message_at DESC')], unique=False)
    op.create_index(op.f('idx_conversations_created_at'), 'conversations', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_conv_history_conversation_id'), 'conversation_history', ['conversation_id'], unique=False)
    op.create_index(op.f('idx_admin_logs_created_at'), 'admin_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_admin_logs_admin_user'), 'admin_logs', ['admin_user_id'], unique=False)
    op.create_index(op.f('idx_admin_logs_action_type'), 'admin_logs', ['action_type'], unique=False)
    op.drop_table('system_settings')
    # ### end Alembic commands ###
