"""Refonte Multi-Boutique

Revision ID: 357475e1722b
Revises: fda3454b19d3
Create Date: 2026-06-09 21:57:59.167851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '357475e1722b'
down_revision: Union[str, Sequence[str], None] = 'fda3454b19d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('TRUNCATE TABLE session CASCADE;')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('documents_embedding_idx'), table_name='documents', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('documents')
    op.drop_index(op.f('ix_pending_media_phone'), table_name='pending_media')
    op.drop_table('pending_media')
    op.drop_table('memoire_conversationnelle')
    op.add_column('conversation', sa.Column('resume_precedent', sa.Text(), nullable=True))
    op.add_column('message', sa.Column('boutique_ciblee_id', sa.UUID(), nullable=True))
    op.add_column('message', sa.Column('type_message', sa.String(length=50), nullable=True))
    op.add_column('message', sa.Column('wa_message_id', sa.String(length=255), nullable=True))
    op.add_column('message', sa.Column('tokens_utilises', sa.Integer(), nullable=True))
    op.add_column('message', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.drop_constraint(op.f('message_whatsapp_message_id_key'), 'message', type_='unique')
    op.create_unique_constraint(None, 'message', ['wa_message_id'])
    op.create_foreign_key(None, 'message', 'boutique', ['boutique_ciblee_id'], ['id'], ondelete='SET NULL')
    op.drop_column('message', 'whatsapp_message_id')
    op.drop_column('message', 'message_type')
    op.add_column('produits', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('produits', sa.Column('instruction_achat', sa.Text(), nullable=True))
    op.add_column('produits', sa.Column('yaburu_produit_id', sa.String(length=255), nullable=True))
    op.add_column('produits', sa.Column('publie_le', sa.DateTime(), nullable=True))
    op.alter_column('produits', 'type_produit',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.add_column('session', sa.Column('utilisateur_id', sa.UUID(), nullable=False))
    op.drop_constraint(op.f('session_boutique_id_fkey'), 'session', type_='foreignkey')
    op.create_foreign_key(None, 'session', 'utilisateur', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    op.drop_column('session', 'boutique_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('boutique_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'session', type_='foreignkey')
    op.create_foreign_key(op.f('session_boutique_id_fkey'), 'session', 'boutique', ['boutique_id'], ['id'], ondelete='SET NULL')
    op.drop_column('session', 'utilisateur_id')
    op.alter_column('produits', 'type_produit',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_column('produits', 'publie_le')
    op.drop_column('produits', 'yaburu_produit_id')
    op.drop_column('produits', 'instruction_achat')
    op.drop_column('produits', 'status')
    op.add_column('message', sa.Column('message_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('message', sa.Column('whatsapp_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_constraint(None, 'message', type_='unique')
    op.create_unique_constraint(op.f('message_whatsapp_message_id_key'), 'message', ['whatsapp_message_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('message', 'is_deleted')
    op.drop_column('message', 'tokens_utilises')
    op.drop_column('message', 'wa_message_id')
    op.drop_column('message', 'type_message')
    op.drop_column('message', 'boutique_ciblee_id')
    op.drop_column('conversation', 'resume_precedent')
    op.create_table('memoire_conversationnelle',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('debut_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fin_index', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taille_fenetre_context', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resumeText', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('date_creation', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('date_mise_a_jour', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], name=op.f('memoire_conversationnelle_conversation_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('memoire_conversationnelle_pkey'))
    )
    op.create_table('pending_media',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('media_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pending_media_pkey'))
    )
    op.create_index(op.f('ix_pending_media_phone'), 'pending_media', ['phone'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey'))
    )
    op.create_index(op.f('documents_embedding_idx'), 'documents', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###
