"""remove_user_id_from_session

Revision ID: 6c372c980c12
Revises: d1bf8669d1a2
Create Date: 2026-05-25 16:18:00.662162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c372c980c12'
down_revision: Union[str, Sequence[str], None] = 'd1bf8669d1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('session_utilisateur_id_fkey'), 'session', type_='foreignkey')
    op.drop_column('session', 'utilisateur_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('utilisateur_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('session_utilisateur_id_fkey'), 'session', 'utilisateur', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
