"""remove_extra_physical_columns_to_strict_uml

Revision ID: 924254c616dc
Revises: 6c372c980c12
Create Date: 2026-05-25 17:59:14.127290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '924254c616dc'
down_revision: Union[str, Sequence[str], None] = '6c372c980c12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('conversation_utilisateur_id_fkey'), 'conversation', type_='foreignkey')
    op.drop_constraint(op.f('conversation_boutique_id_fkey'), 'conversation', type_='foreignkey')
    op.drop_column('conversation', 'boutique_id')
    op.drop_column('conversation', 'utilisateur_id')
    op.drop_constraint(op.f('memoire_conversationnelle_utilisateur_id_fkey'), 'memoire_conversationnelle', type_='foreignkey')
    op.drop_column('memoire_conversationnelle', 'utilisateur_id')
    op.drop_constraint(op.f('message_utilisateur_id_fkey'), 'message', type_='foreignkey')
    op.drop_column('message', 'utilisateur_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('utilisateur_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('message_utilisateur_id_fkey'), 'message', 'utilisateur', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    op.add_column('memoire_conversationnelle', sa.Column('utilisateur_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('memoire_conversationnelle_utilisateur_id_fkey'), 'memoire_conversationnelle', 'utilisateur', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    op.add_column('conversation', sa.Column('utilisateur_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('conversation', sa.Column('boutique_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('conversation_boutique_id_fkey'), 'conversation', 'boutique', ['boutique_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('conversation_utilisateur_id_fkey'), 'conversation', 'utilisateur', ['utilisateur_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
