"""Sync models with SQL schema

Revision ID: b5b6539c590a
Revises: cedfba485f82
Create Date: 2026-05-10 07:07:56.968779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b5b6539c590a'
down_revision: Union[str, Sequence[str], None] = 'cedfba485f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('admin_logs', 'meta_data')
    op.drop_column('messages', 'meta_data')
    op.alter_column('stores', 'yaburu_access_token',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stores', 'yaburu_access_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('messages', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('admin_logs', sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('admin_logs', 'metadata')
    # ### end Alembic commands ###
