"""align_with_uml_schema

Revision ID: d1bf8669d1a2
Revises: 0533b6b4f641
Create Date: 2026-05-25 16:09:49.396256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'd1bf8669d1a2'
down_revision: Union[str, Sequence[str], None] = '0533b6b4f641'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS active_conversations_summary CASCADE")
    op.execute("DROP TABLE IF EXISTS conversations CASCADE")
    op.execute("DROP TABLE IF EXISTS conversation_history CASCADE")
    op.execute("DROP TABLE IF EXISTS stores CASCADE")
    op.execute("DROP TABLE IF EXISTS sessions CASCADE")
    op.execute("DROP TABLE IF EXISTS users CASCADE")
    op.execute("DROP TABLE IF EXISTS messages CASCADE")

    op.create_table('utilisateur',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('prenom', sa.String(length=100), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('integration_etape', sa.String(length=50), nullable=True),
    sa.Column('derniere_vue', sa.DateTime(), nullable=True),
    sa.Column('langue', sa.String(length=10), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_suppression', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('temp_email', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telephone')
    )
    op.create_table('boutique',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('yaburu_boutique_id', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('boutique_nom', sa.String(length=255), nullable=True),
    sa.Column('boutique_description', sa.Text(), nullable=True),
    sa.Column('boutique_url', sa.String(length=500), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('yaburu_access_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yaburu_boutique_id')
    )
    op.create_table('produits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('boutique_id', sa.UUID(), nullable=False),
    sa.Column('type_produit', sa.String(length=20), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=200), nullable=True),
    sa.Column('nom', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quantite', sa.Integer(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutique.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('boutique_id', sa.UUID(), nullable=True),
    sa.Column('session_token', sa.String(length=512), nullable=False),
    sa.Column('est_active', sa.Boolean(), nullable=True),
    sa.Column('expire_le', sa.DateTime(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutique.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('conversation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('boutique_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('debut_le', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('fini_le', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('dernier_message_le', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['boutique_id'], ['boutique.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memoire_conversationnelle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('debut_index', sa.Integer(), nullable=True),
    sa.Column('fin_index', sa.Integer(), nullable=True),
    sa.Column('taille_fenetre_context', sa.Integer(), nullable=True),
    sa.Column('resumeText', sa.Text(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('message',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('utilisateur_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('whatsapp_message_id')
    )
    op.create_table('outils_executees',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('outil_nom', sa.String(length=50), nullable=False),
    sa.Column('outil_entree', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('outil_sortie', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('message_erreur', sa.Text(), nullable=True),
    sa.Column('execution_temps', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recherche_contextuelle',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('requete', sa.Text(), nullable=False),
    sa.Column('requete_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.Column('documents_trouve', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('seuil_de_similarite', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('documents_utilises', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_mise_a_jour', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['message.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'admin_logs', 'utilisateur', ['admin_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'rag_retrievals', 'conversation', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'rag_retrievals', 'utilisateur', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'rag_retrievals', 'message', ['message_id'], ['id'], ondelete='SET NULL')
    op.add_column('usage_stats', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'usage_stats', 'utilisateur', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'usage_stats', 'boutique', ['store_id'], ['id'], ondelete='SET NULL')
    op.drop_column('usage_stats', 'shop_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage_stats', sa.Column('shop_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'usage_stats', type_='foreignkey')
    op.drop_constraint(None, 'usage_stats', type_='foreignkey')
    op.create_foreign_key(op.f('usage_stats_shop_id_fkey'), 'usage_stats', 'stores', ['shop_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('usage_stats_user_id_fkey'), 'usage_stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('usage_stats', 'store_id')
    op.drop_constraint(None, 'rag_retrievals', type_='foreignkey')
    op.drop_constraint(None, 'rag_retrievals', type_='foreignkey')
    op.drop_constraint(None, 'rag_retrievals', type_='foreignkey')
    op.create_foreign_key(op.f('rag_retrievals_message_id_fkey'), 'rag_retrievals', 'messages', ['message_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('rag_retrievals_user_id_fkey'), 'rag_retrievals', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('rag_retrievals_conversation_id_fkey'), 'rag_retrievals', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'admin_logs', type_='foreignkey')
    op.create_foreign_key(op.f('admin_logs_admin_user_id_fkey'), 'admin_logs', 'users', ['admin_user_id'], ['id'], ondelete='SET NULL')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=50), server_default=sa.text("'text'::character varying"), autoincrement=False, nullable=True),
    sa.Column('format', sa.VARCHAR(length=20), server_default=sa.text("'plain'::character varying"), autoincrement=False, nullable=True),
    sa.Column('whatsapp_message_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('whatsapp_status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('messages_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey')),
    sa.UniqueConstraint('whatsapp_message_id', name=op.f('messages_whatsapp_message_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('language_preference', sa.VARCHAR(length=10), server_default=sa.text("'fr'::character varying"), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=50), server_default=sa.text("'Africa/Porto-Novo'::character varying"), autoincrement=False, nullable=True),
    sa.Column('last_seen_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('onboarding_step', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('temp_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey')),
    sa.UniqueConstraint('email', name=op.f('users_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('phone_number', name=op.f('users_phone_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_token', sa.VARCHAR(length=512), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('last_activity_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('sessions_shop_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sessions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_pkey')),
    sa.UniqueConstraint('session_token', name=op.f('sessions_session_token_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('stores',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('yaburu_store_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('yaburu_access_token', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('token_expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('store_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('store_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('store_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('last_sync_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('sync_status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('shops_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('shops_pkey')),
    sa.UniqueConstraint('yaburu_store_id', name=op.f('shops_yaburu_shop_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('conversation_history',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('conversation_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('end_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('window_size', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=True),
    sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('full_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('conversation_history_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversation_history_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversation_history_pkey'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('store_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('conversations_session_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('conversations_shop_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('conversations_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('conversations_pkey'))
    )
    op.drop_table('recherche_contextuelle')
    op.drop_table('outils_executees')
    op.drop_table('message')
    op.drop_table('memoire_conversationnelle')
    op.drop_table('conversation')
    op.drop_table('session')
    op.drop_table('produits')
    op.drop_table('boutique')
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
