"""add_message_queue_and_concurrency_lock

Revision ID: fda3454b19d3
Revises: 924254c616dc
Create Date: 2026-05-28 06:58:58.203156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fda3454b19d3'
down_revision: Union[str, Sequence[str], None] = '924254c616dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_d_attente_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('audio_data', sa.Text(), nullable=True),
    sa.Column('image_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_d_attente_messages_phone'), 'file_d_attente_messages', ['phone'], unique=False)
    op.add_column('utilisateur', sa.Column('traitement_en_cours', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('utilisateur', 'traitement_en_cours')
    op.drop_index(op.f('ix_file_d_attente_messages_phone'), table_name='file_d_attente_messages')
    op.drop_table('file_d_attente_messages')
    # ### end Alembic commands ###
